api:
  # -t the target API definition
  target: Connect2ID-IDPorten.postman_collection.json
  # -f the API format, openapi, soap, or graphql
  format: openapi
  # -S safe mode this will skip the active scan and perform a baseline scan
  safe: true
  # -c config file
  config: zap-tk-api.conf
  # -d show debug messages
  debug: true
  # -s short output
  short: false
  # -l minimum level to show: PASS, IGNORE, INFO, WARN or FAIL
  level: INFO
  # -n context file
  # context: /data/uploads/context.conf
  # username to use for authenticated scans
  user: anonymous
  # delay in seconds to wait for passive scanning
  delay: 5
  # max time in minutes to wait for ZAP to start and the passive scan to run
  time: 60
  # ZAP command line options
  zap_options: -config aaa=bbb
  # -I should ZAP fail on warnings
  fail_on_warn: false
